### ISSUE TITLE
Support for pytest-xdist

### ISSUE THREAD

**Issue by nicoddemus** [nicoddemus/pytest-rich#6]
Make sure pytest-rich works with pytest-xdist.

I suspect we can get this support without any special code, given how pytest-rich currently leverages rich's live/progress features.

**Comment by AngellusMortis** [comment]
Can confirm, this does _not_ work with xdist. I get an error like the following:

```
INTERNALERROR> Traceback (most recent call last):
INTERNALERROR>   File "/usr/local/lib/python3.10/site-packages/_pytest/main.py", line 268, in wrap_session
INTERNALERROR>     session.exitstatus = doit(config, session) or 0
INTERNALERROR>   File "/usr/local/lib/python3.10/site-packages/_pytest/main.py", line 322, in _main
INTERNALERROR>     config.hook.pytest_runtestloop(session=session)
INTERNALERROR>   File "/usr/local/lib/python3.10/site-packages/pluggy/_hooks.py", line 265, in __call__
INTERNALERROR>     return self._hookexec(self.name, self.get_hookimpls(), kwargs, firstresult)
INTERNALERROR>   File "/usr/local/lib/python3.10/site-packages/pluggy/_manager.py", line 80, in _hookexec
INTERNALERROR>     return self._inner_hookexec(hook_name, methods, kwargs, firstresult)
INTERNALERROR>   File "/usr/local/lib/python3.10/site-packages/pluggy/_callers.py", line 60, in _multicall
INTERNALERROR>     return outcome.get_result()
INTERNALERROR>   File "/usr/local/lib/python3.10/site-packages/pluggy/_result.py", line 60, in get_result
INTERNALERROR>     raise ex[1].with_traceback(ex[2])
INTERNALERROR>   File "/usr/local/lib/python3.10/site-packages/pluggy/_callers.py", line 39, in _multicall
INTERNALERROR>     res = hook_impl.function(*args)
INTERNALERROR>   File "/usr/local/lib/python3.10/site-packages/xdist/dsession.py", line 117, in pytest_runtestloop
INTERNALERROR>     self.loop_once()
INTERNALERROR>   File "/usr/local/lib/python3.10/site-packages/xdist/dsession.py", line 140, in loop_once
INTERNALERROR>     call(**kwargs)
INTERNALERROR>   File "/usr/local/lib/python3.10/site-packages/xdist/dsession.py", line 266, in worker_logstart
INTERNALERROR>     self.config.hook.pytest_runtest_logstart(nodeid=nodeid, location=location)
INTERNALERROR>   File "/usr/local/lib/python3.10/site-packages/pluggy/_hooks.py", line 265, in __call__
INTERNALERROR>     return self._hookexec(self.name, self.get_hookimpls(), kwargs, firstresult)
INTERNALERROR>   File "/usr/local/lib/python3.10/site-packages/pluggy/_manager.py", line 80, in _hookexec
INTERNALERROR>     return self._inner_hookexec(hook_name, methods, kwargs, firstresult)
INTERNALERROR>   File "/usr/local/lib/python3.10/site-packages/pluggy/_callers.py", line 60, in _multicall
INTERNALERROR>     return outcome.get_result()
INTERNALERROR>   File "/usr/local/lib/python3.10/site-packages/pluggy/_result.py", line 60, in get_result
INTERNALERROR>     raise ex[1].with_traceback(ex[2])
INTERNALERROR>   File "/usr/local/lib/python3.10/site-packages/pluggy/_callers.py", line 39, in _multicall
INTERNALERROR>     res = hook_impl.function(*args)
INTERNALERROR>   File "/usr/local/lib/python3.10/site-packages/pytest_rich.py", line 174, in pytest_runtest_logstart
INTERNALERROR>     self._update_task(nodeid)
INTERNALERROR>   File "/usr/local/lib/python3.10/site-packages/pytest_rich.py", line 194, in _update_task
INTERNALERROR>     task = self.runtest_tasks_per_file[fn]
INTERNALERROR> KeyError: PosixPath('/app/tests/test_package.py')
```

I do really hope someone picks up the package and maintains it as I think this definitely has a lot of potential vs. pytest-sugar.

**Comment by joshuadavidthomas** [comment]
Yeah, this is definitely on the roadmap.

I've been a bit underwater with my dayjob[^0], so I haven't had much time lately to devote to OSS projects.

Any PRs to tackle this issue are welcome!

[^0]: Two projects launching simultaneously in March, why I did this to myself I will never know. 😬

**Comment by nicoddemus** [comment]
> I've been a bit underwater with my dayjob

No worries, take your time! Thanks for the update. 👍

**Comment by joshuadavidthomas** [comment]
@nicoddemus Any tips about what I should be looking at within `pytest-xdist`? I've only ever been a user of it, never looked at the source. As the lead contributor, I assume you know the internals pretty well 😄 -- anything I need to know or be aware of?

**Comment by nicoddemus** [comment]
My suggestion is to do what you are already doing, follow pytest-sugar's lead here. :grin:
